[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts",
    "@thrackle-io/forte-rules-engine/=node_modules/@thrackle-io/forte-rules-engine"
]